#!/bin/bash
# Demo of the new --view mode feature

echo "============================================"
echo "ComicInfoEdit.py --view Mode Demo"
echo "============================================"
echo ""
echo "The new --view mode lets you quickly check metadata"
echo "without having to open Windows/WinRAR!"
echo ""
echo "============================================"
echo "Basic Usage"
echo "============================================"
echo ""
echo "# View metadata from a single CBZ file"
echo "./ComicInfoEdit.py comic.cbz --view"
echo ""
echo "Example output:"
echo ""
echo "Archive: Amazing_Spider-Man_001.cbz"
echo "ComicInfo.xml found ✓"
echo ""
echo "Metadata:"
echo "  Series: Amazing Spider-Man"
echo "  Number: 1"
echo "  Volume: 2018"
echo "  Summary: Peter Parker faces his greatest challenge yet..."
echo "  Publisher: Marvel Comics"
echo "  Writer: Dan Slott"
echo "  Penciller: Humberto Ramos"
echo "  Year: 2018"
echo "  Month: 4"
echo "  PageCount: 24"
echo "  LanguageISO: en"
echo ""
echo "============================================"
echo "Key Features"
echo "============================================"
echo ""
echo "✓ Read-only operation (no modifications)"
echo "✓ No backup/restore overhead"
echo "✓ Fast - only extracts ComicInfo.xml"
echo "✓ Works with both CBZ and CBR files"
echo "✓ Shows all populated metadata fields"
echo "✓ Truncates long values for readability"
echo "✓ Clean, terminal-friendly output"
echo "✓ Single file only (no wildcard patterns)"
echo ""
echo "============================================"
echo "Use Cases"
echo "============================================"
echo ""
echo "1. Quick check before modifying:"
echo "   ./ComicInfoEdit.py comic.cbz --view"
echo "   # See what's there first"
echo "   ./ComicInfoEdit.py comic.cbz --attribute Publisher=\"Marvel\""
echo ""
echo "2. Verify after changes:"
echo "   ./ComicInfoEdit.py comic.cbz --attribute Series=\"Batman\""
echo "   ./ComicInfoEdit.py comic.cbz --view"
echo "   # Confirm the change"
echo ""
echo "3. Check if file has ComicInfo.xml:"
echo "   ./ComicInfoEdit.py unknown.cbz --view"
echo "   # Shows 'ComicInfo.xml not found ✗' if missing"
echo ""
echo "============================================"
echo "Error Handling"
echo "============================================"
echo ""
echo "# Must be a single file (not a directory)"
echo "$ ./ComicInfoEdit.py /comics --view"
echo "Error: --view mode requires a file, not a directory"
echo ""
echo "# Must be exactly one file"
echo "$ ./ComicInfoEdit.py comic1.cbz comic2.cbz --view"
echo "Error: --view mode requires exactly one file path"
echo ""
echo "# Must be a comic file"
echo "$ ./ComicInfoEdit.py document.pdf --view"
echo "Error: Not a comic file: document.pdf"
echo ""
echo "============================================"
echo "Workflow Example"
echo "============================================"
echo ""
echo "# You're at the terminal, about to modify a file"
echo "# Instead of switching to Windows/WinRAR..."
echo ""
echo "$ ./ComicInfoEdit.py \"Batman #1.cbz\" --view"
echo ""
echo "Archive: Batman #1.cbz"
echo "ComicInfo.xml found ✓"
echo ""
echo "Metadata:"
echo "  Series: Batman"
echo "  Volume: 2016"
echo "  Publisher: DC"
echo ""
echo "# Good! Now I know what's there."
echo "# I can add missing fields:"
echo ""
echo "$ ./ComicInfoEdit.py \"Batman #1.cbz\" --attribute Number=1 Writer=\"Tom King\""
echo ""
echo "# Quick check to verify:"
echo "$ ./ComicInfoEdit.py \"Batman #1.cbz\" --view"
echo ""
echo "Archive: Batman #1.cbz"
echo "ComicInfo.xml found ✓"
echo ""
echo "Metadata:"
echo "  Series: Batman"
echo "  Number: 1"
echo "  Volume: 2016"
echo "  Publisher: DC"
echo "  Writer: Tom King"
echo ""
echo "# Perfect! All done without leaving the terminal."
echo ""
echo "============================================"
echo ""
echo "This feature is perfect for your workflow!"
echo "Stay in the terminal, work faster! 🚀"
echo ""